name = "plyml-site"
main = "src/worker.js"
compatibility_date = "2025-09-06"

assets = { directory = "./site" }
workers_dev = true

account_id = "3163c47e268d21d781c4fd86a71964cb"
# Serve both apex and www through this Worker:
routes = [
  { pattern = "plyml.com/*", zone_name = "plyml.com" },
  { pattern = "www.plyml.com/*", zone_name = "plyml.com" }
]
